namespace VirtualMicroBroker;

// Generated by scripts/generate-virtual-audio-payload-hashes.js.
internal static partial class AudioDriverPayloadHashes
{
    internal static IReadOnlyDictionary<string, string> ExpectedSha256 { get; } =
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["CodexRemoteVirtualAudio.sys"] = "811FB9784446B64C930503E440B357EA076EDBE292DFF548F878136D5B68BDE1",
            ["CodexRemoteVirtualAudio.inf"] = "D86D1D01FE20600F28E3ACB194B3CF9F7790C3C7AAF685EC56E10C0EDFA193C6",
            ["CodexRemoteVirtualAudio.cat"] = "54D3CB45F9DA28FB5C28D591E7AD14CFF27590A0B6CD7B746A00A681EE67C76F",
        };
}
