#pragma once
#include <devioctl.h>
#define CRVM_MAGIC 0x314D4356UL
#define CRVM_VERSION 1U
#define CRVM_REPORT_LENGTH 64U
#define CRVM_MAX_BATCH_REPORTS 64U
#define CRVM_OUTPUT_QUEUE_CAPACITY 32U
#define CRVM_FLAG_READY 1UL
#define CRVM_FLAG_TRANSPORT_RESET 4UL
#define CRVM_OUTPUT_INCLUDED_REPORT_ID 1UL
#define CRVM_OUTPUT_EXCLUDED_REPORT_ID 2UL
// {E2A7CB54-8420-4D51-9DD8-D6575B9251D1}
DEFINE_GUID(GUID_DEVINTERFACE_CODEXREMOTE_VMICRO,0xe2a7cb54,0x8420,0x4d51,0x9d,0xd8,0xd6,0x57,0x5b,0x92,0x51,0xd1);
#define IOCTL_CRVM_GET_INFO CTL_CODE(FILE_DEVICE_UNKNOWN,0x800,METHOD_BUFFERED,FILE_READ_DATA|FILE_WRITE_DATA)
#define IOCTL_CRVM_SUBMIT_INPUT CTL_CODE(FILE_DEVICE_UNKNOWN,0x801,METHOD_BUFFERED,FILE_READ_DATA|FILE_WRITE_DATA)
#define IOCTL_CRVM_READ_OUTPUT CTL_CODE(FILE_DEVICE_UNKNOWN,0x802,METHOD_BUFFERED,FILE_READ_DATA|FILE_WRITE_DATA)
#define IOCTL_CRVM_RESET_TRANSPORT CTL_CODE(FILE_DEVICE_UNKNOWN,0x804,METHOD_BUFFERED,FILE_READ_DATA|FILE_WRITE_DATA)
#pragma pack(push,1)
typedef struct _CRVM_INFO {ULONG Magic;USHORT Version;USHORT Size;UINT64 ConnectionEpoch;UINT64 LastBatchSequence;UINT64 OutputSequence;ULONG DroppedOutputReports;ULONG Flags;} CRVM_INFO;
typedef struct _CRVM_BATCH_HEADER {ULONG Magic;USHORT Version;USHORT ReportCount;UINT64 Sequence;} CRVM_BATCH_HEADER;
typedef struct _CRVM_SUBMIT_RESULT {ULONG Magic;USHORT Version;USHORT Size;UINT64 Sequence;ULONG Disposition;ULONG AcceptedReports;LONG FirstFailureStatus;ULONG Reserved;} CRVM_SUBMIT_RESULT;
typedef struct _CRVM_OUTPUT_RECORD {ULONG Magic;USHORT Version;USHORT Size;UINT64 Sequence;UINT64 PerformanceCounter;ULONG OriginalLength;ULONG Flags;UCHAR WireReport[CRVM_REPORT_LENGTH];} CRVM_OUTPUT_RECORD;
#pragma pack(pop)
C_ASSERT(sizeof(CRVM_INFO)==40);C_ASSERT(sizeof(CRVM_BATCH_HEADER)==16);C_ASSERT(sizeof(CRVM_SUBMIT_RESULT)==32);C_ASSERT(sizeof(CRVM_OUTPUT_RECORD)==96);
